spring:
  cache:
    redis:
      time-to-live: 3600s #默认为从不过期
  datasource:
    url: jdbc:mysql://127.0.0.1/app?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
    username: admin
    password: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    jpa:
      repositories:
        enabled: true



  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#mybatis.configuration.mapUnderscoreToCamelCase: true



logging:
  file: target/app.log
  level:
    ROOT: INFO
    com.rdd.pia: INFO
    com.rdd.pia.filter: INFO
    com.rdd.pia.services: INFO

#redis:
#  host: localhost
#  port:6379
 # jedis:
 #   pool:
  #    max-active: 5

#      max-wait: 10000